export const HOTELS_REQUEST = 'HOTELS_REQUEST';
export const HOTELS_SUCCESS = 'HOTELS_SUCCESS';
export const HOTELS_FAILURE = 'HOTELS_FAILURE';

export const HOTELS_ADD_REQUEST = 'HOTELS_ADD_REQUEST';
export const HOTELS_EDIT_REQUEST = 'HOTELS_EDIT_REQUEST';
export const HOTELS_DELETE_REQUEST = 'HOTELS_DELETE_REQUEST';
export const HOTELS_ADD_SUCCESS = 'HOTELS_ADD_SUCCESS';
export const HOTELS_EDIT_SUCCESS = 'HOTELS_EDIT_SUCCESS';
export const HOTELS_DELETE_SUCCESS = 'HOTELS_DELETE_SUCCESS';
export const HOTELS_ADD_FAILURE = 'HOTELS_ADD_FAILURE';
export const HOTELS_EDIT_FAILURE = 'HOTELS_EDIT_FAILURE';
export const HOTELS_DELETE_FAILURE = 'HOTELS_DELETE_FAILURE';

export const USER_SET_REQUEST = 'USER_SET_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ADMIN_SUCCESS = 'ADMIN_SUCCESS';
export const AL_SUCCESS = 'AL_SUCCESS';
export const BOOKINGS_SUCCESS = 'BOOKINGS_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const REG_REQUEST = 'REG_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const REG_SUCCESS = 'REG_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const REG_FAILURE = 'REG_FAILURE';

export const BOOKINGS_SET_REQUEST = 'BOOKINGS_SET_REQUEST';
export const BOOKINGS_SET_SUCCESS = 'BOOKINGS_SET_SUCCESS';
export const BOOKINGS_SET_FAILURE = 'BOOKINGS_SET_FAILURE';
