export const HOTELS_REQUEST = 'HOTELS_REQUEST';
export const HOTELS_SUCCESS = 'HOTELS_SUCCESS';
export const HOTELS_FAILURE = 'HOTELS_FAILURE';

export const HOTELS_ADD_REQUEST = 'HOTELS_ADD_REQUEST';
export const HOTELS_EDIT_REQUEST = 'HOTELS_EDIT_REQUEST';
export const HOTELS_DELETE_REQUEST = 'HOTELS_DELETE_REQUEST';
export const HOTELS_ADD_SUCCESS = 'HOTELS_ADD_SUCCESS';
export const HOTELS_EDIT_SUCCESS = 'HOTELS_EDIT_SUCCESS';
export const HOTELS_DELETE_SUCCESS = 'HOTELS_DELETE_SUCCESS';
export const HOTELS_ADD_FAILURE = 'HOTELS_ADD_FAILURE';
export const HOTELS_EDIT_FAILURE = 'HOTELS_EDIT_FAILURE';
export const HOTELS_DELETE_FAILURE = 'HOTELS_DELETE_FAILURE';

export const USER_SET_REQUEST = 'USER_SET_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ADMIN_SUCCESS = 'ADMIN_SUCCESS';
export const AL_SUCCESS = 'AL_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';
